name: grid_world
description: A toolkit for playing with Conway's Game of Life at the command line.
version: 0.1.3
homepage: https://github.com/monopole/grid_world

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.0.0

dependencies:
  test: ^1.9.4
