name: grid_world
description: A cellular automaton library associated with a square grid.  Includes Conway's Game of Life.
version: 1.1.0
homepage: https://github.com/monopole/grid_world

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1

dependencies:
  tuple: ^2.0.0
