name: grid_world
description: A cellular automaton library associated with a square grid.  Includes Conway's Game of Life.
version: 0.1.10
homepage: https://github.com/monopole/grid_world

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.0.0

dependencies:
  test: ^1.9.4
  tuple: ^1.0.3
