name: grid_world
description: conway's game of life
version: 0.0.2
homepage: https://github.com/monopole/grid_world

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.0.0

dependencies:
  test: ^1.9.4
